// <auto-generated />
using System;
using Crm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20250801000001_CreateCoreCrmTables")]
    partial class CreateCoreCrmTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Crm.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Address").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasColumnType("text");
                    b.Property<string>("Industry").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Tags").IsRequired().HasColumnType("text");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Crm.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid?>("CompanyId").HasColumnType("uuid");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasColumnType("text");
                    b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("Phone").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("Position").HasColumnType("text");
                    b.Property<string>("Tags").IsRequired().HasColumnType("text");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Crm.Domain.Entities.Deal", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<decimal>("Amount").HasColumnType("numeric");
                    b.Property<DateTime?>("CloseDate").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("CompanyId").HasColumnType("uuid");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasColumnType("text");
                    b.Property<Guid?>("ContactId").HasColumnType("uuid");
                    b.Property<string>("Currency").IsRequired().HasMaxLength(10).HasColumnType("character varying(10)");
                    b.Property<Guid?>("OwnerId").HasColumnType("uuid");
                    b.Property<int>("Probability").HasColumnType("integer");
                    b.Property<Guid>("StageId").HasColumnType("uuid");
                    b.Property<int>("Status").HasColumnType("integer");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.HasKey("Id");
                    b.ToTable("Deals");
                });

            modelBuilder.Entity("Crm.Domain.Entities.Pipeline", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.ToTable("Pipelines");
                });

            modelBuilder.Entity("Crm.Domain.Entities.Stage", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<int>("Order").HasColumnType("integer");
                    b.Property<Guid>("PipelineId").HasColumnType("uuid");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("PipelineId", "Order").IsUnique();
                    b.ToTable("Stages");
                });

            modelBuilder.Entity("Crm.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasColumnType("text");
                    b.Property<DateTime?>("DueAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("OwnerId").HasColumnType("uuid");
                    b.Property<int>("Priority").HasColumnType("integer");
                    b.Property<Guid?>("RelatedId").HasColumnType("uuid");
                    b.Property<int>("RelatedTo").HasColumnType("integer");
                    b.Property<int>("Status").HasColumnType("integer");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.HasKey("Id");
                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Crm.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("BlobRef").HasColumnType("text");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasColumnType("text");
                    b.Property<string>("ContentType").HasColumnType("text");
                    b.Property<string>("FileName").IsRequired().HasColumnType("text");
                    b.Property<Guid?>("RelatedId").HasColumnType("uuid");
                    b.Property<int>("RelatedTo").HasColumnType("integer");
                    b.Property<long>("Size").HasColumnType("bigint");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.Property<string>("Url").HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Crm.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.HasKey("Id");
                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Crm.Domain.Entities.UserTeam", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasColumnType("text");
                    b.Property<Guid>("TeamId").HasColumnType("uuid");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "TeamId").IsUnique();
                    b.ToTable("UserTeams");
                });

            modelBuilder.Entity("Crm.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().IsRequired().HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("SettingsJson").HasColumnType("text");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.HasKey("Id");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Crm.Infrastructure.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Action").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("ChangesJson").HasColumnType("text");
                    b.Property<string>("CorrelationId").HasColumnType("text");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Entity").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("EntityId").IsRequired().HasColumnType("text");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.Property<string>("UserId").HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("TenantId", "Entity", "EntityId", "CreatedAtUtc");
                    b.ToTable("AuditEntries");
                });
        }
    }
}
