// <auto-generated/>
namespace Crm.UI.Components.Base
{
    using Microsoft.AspNetCore.Components;

    using System.Collections.Generic;

    public partial class UiToast
    {
        [Parameter] 
        public string? Title { get; set; }

        [Parameter] 
        public string? Message { get; set; }

        [Parameter] 
        public string Tone { get; set; } = "info";

        [Parameter] 
        public string? Class { get; set; }

        [Parameter] 
        public RenderFragment? ChildContent { get; set; }

        [Parameter(CaptureUnmatchedValues = true)] 
        public Dictionary<string, object>? AdditionalAttributes { get; set; }

        private string ToneClass => Tone switch
        {
            "success" => "border-emerald-500",
            "warning" => "border-amber-500",
            "danger" => "border-rose-500",
            _ => "border-indigo-500"
        };
    }
}