// <auto-generated/>
namespace Crm.Web.Components
{
    using Microsoft.AspNetCore.Components;

    public partial class Modal
    {
        private bool _open;

        [Parameter] public string? Title { get; set; }
        [Parameter] public RenderFragment? ChildContent { get; set; }
        [Parameter] public RenderFragment? Footer { get; set; }

        public void Show() { _open = true; StateHasChanged(); }
        public void Hide() { _open = false; StateHasChanged(); }
        private void Close() => Hide();
    }
}