// <auto-generated/>
namespace Crm.UI.Components
{
    using Microsoft.AspNetCore.Components;

    using System;
    using System.Linq;

    public partial class EntityHeader
    {
        [Parameter] 
        public string Title { get; set; } = string.Empty;

        [Parameter] 
        public string? Subtitle { get; set; }

        private string Initials => string.Join(string.Empty, Title.Split(' ', StringSplitOptions.RemoveEmptyEntries).Select(s => s[0])).ToUpperInvariant();
    }
}